### ISSUE TITLE
Fix all critical dependabot alerts

### ISSUE THREAD

**Issue by dforsten** [DMDcoin/diamond-node#92]
Dependabot currently reports 52 issues, 9 of which are critical.
Fix all critical issues.

**Comment by dforsten** [comment]
8 of the 9 critical issues should now be fixed.
The rust-crypto issue looks more complex, will dig into it next.

**Comment by dforsten** [comment]
The most straight-forward fix seems to be to use "parity-crypto" instead, which is already used in the repository. Investigating why "rust-crypto" is still being used, and how easily it could be switched out with "parity-crypto".

**Comment by SurfingNerd** [comment]
thanks, critical errors went down from 9 to 5.

**Comment by SurfingNerd** [comment]
parity-daemonize is forked here, https://github.com/DMDcoin/parity-daemonize
so we can solve the CVEs connected with the "failure" crate.
