### ISSUE TITLE
Migrate "threshold-crypto" crate from "failure" to "thiserror"

### ISSUE THREAD

**Issue by dforsten** [DMDcoin/diamond-node#95]
Critical issue reported by dependabot.

**Comment by dforsten** [comment]
Already fixed with the newest commit on the "threshold-crypto" repo, but it is not labeled as a new version.
The "hbbft" crate needs to be patched to use that newest commit instead.

**Comment by dforsten** [comment]
The "fedmint" project maintains private forks of hbbft/threshold-crypto as well,
we may want to do the same:
https://github.com/fedimint

**Comment by dforsten** [comment]
I implemented the necessary changes, creating a PR to the poanetwork/hbbft repo.
In the meantime the changes are available on my private fork at:
https://github.com/dforsten/hbbft

**Comment by dforsten** [comment]
PR for the poanetwork hbbft repo submitted here:
https://github.com/poanetwork/hbbft/pull/441

**Comment by SurfingNerd** [comment]
no critical issues anymore
